FROM almalinux:9

RUN --mount=type=bind,source=packages,target=/tmp/packages,readonly \
    dnf -y clean metadata \
    && dnf -y install dnf-plugins-core \
    &&  dnf -y install https://repo.osg-htc.org/osg/25-main/osg-25-main-el9-release-latest.rpm \
    && curl -LO \
        https://software.igwn.org/lscsoft/rocky/9/production/x86_64/os/Packages/i/igwn-production-config-9-5.el9.noarch.rpm \
    && rpm --install igwn-production-config-9-5.el9.noarch.rpm \
    && rm -f igwn-production-config-9-5.el9.noarch.rpm \
    && dnf -y install \
        epel-release \
        python39 \
        pciutils \
        python3-pip \
        python3-devel \
        boost-python3 \
        jq \
        procps \
    && dnf -y install python3-igwn-auth-utils \
        htgettoken \
        gwdatafind \
        pelican \
    && xargs -r dnf -y install < /tmp/packages \
    && dnf config-manager --add-repo \
        https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo \
    && dnf -y install cuda-toolkit-12-4 \
    && dnf -y module install nvidia-driver:580-dkms \
    && dnf search voms \
    && dnf -y install voms-clients-cpp \
    && dnf -y clean all \
    && rm -rf /var/cache/dnf /var/cache/yum

WORKDIR /

ENV CONDA_DIR=/opt/conda
ENV PATH=/opt/conda/bin:/usr/local/cuda-12.4/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:$LD_LIBRARY_PATH
ENV CONDA_OVERRIDE_CUDA=12.4

RUN curl -fsSL \
        https://repo.anaconda.com/miniconda/Miniconda3-py311_25.3.1-1-Linux-x86_64.sh \
        -o /tmp/miniconda.sh \
    && /bin/bash /tmp/miniconda.sh -b -p "$CONDA_DIR" \
    && rm -f /tmp/miniconda.sh \
    && conda install -y -c conda-forge \
        python==3.11.13 \
        jupyterlab==4.5.2 \
        nodejs==20.9.0 \
        jupyterhub==5.4.3 \
        davix==0.8.6 \
        xrootd==5.5.5 \
        gfal2==2.21.3 \
        gfal2-util==1.9.0 \
        python-gfal2==1.12.0 \
        apptainer==1.4.4 \
    && python -m pip install --no-cache-dir \
        rucio==41.1.1 \
        rucio-clients==41.1.1 \
        rucio-jupyterlab==41.0.0 \
        ksmm==1.0.0 \
    && conda clean -afy \
    && rm -rf /root/.cache/pip

RUN printf '\nconda activate base\n' >> /root/.bashrc \
    && mkdir -p /root/.ipython /root/.init

ENV TINI_VERSION=v0.19.0
RUN curl -fsSL \
        "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini" \
        -o /bin/tini \
    && chmod +x /bin/tini

COPY --chmod=0755 ./jupyterhub-singleuser.sh /usr/local/bin/jupyterhub-singleuser.sh
COPY --chmod=0755 ./jupyterhub-singleuser /usr/local/bin/jupyterhub-singleuser
COPY --chmod=0755 ./spawn.sh /root/.init/spawn.sh

RUN ln -s /cvmfs/grid.cern.ch/etc/grid-security/vomses/ /etc/ \
    && rm -rf /etc/grid-security/vomsdir/ \
    && ln -s /cvmfs/grid.cern.ch/etc/grid-security/vomsdir/ /etc/grid-security/ \
    && ln -s /cvmfs/grid.cern.ch/etc/grid-security/certificates/ /etc/grid-security/

COPY ./config/jupyter_notebook_config.json /opt/conda/etc/jupyter/jupyter_notebook_config.json

COPY ./singularity-kernel/ /opt/conda/share/jupyter/kernels/singularity-kernel/
COPY ./singularity-kernel-ROOT/ /opt/conda/share/jupyter/kernels/singularity-kernel-ROOT/
COPY ./singularity-kernel-wdf/ /opt/conda/share/jupyter/kernels/singularity-kernel-wdf/
COPY ./singularity-kernel-igwn/ /opt/conda/share/jupyter/kernels/singularity-kernel-igwn/

RUN jupyter kernelspec install /opt/conda/share/jupyter/kernels/singularity-kernel/ \
    && jupyter kernelspec install /opt/conda/share/jupyter/kernels/singularity-kernel-ROOT/ \
    && jupyter kernelspec install /opt/conda/share/jupyter/kernels/singularity-kernel-wdf/ \
    && jupyter kernelspec install /opt/conda/share/jupyter/kernels/singularity-kernel-igwn/

COPY ./config/rucio.cfg /opt/rucio/etc/rucio.cfg

WORKDIR /opt/workspace
