name: build-images

on:
  push:
    tags:
      - "*"
  workflow_dispatch:


jobs:
  build-images:
    runs-on: self-hosted
    strategy:
      matrix:
        include:          
          - name: jupyterlab-image-alma9-cpu-with-root
            context: ./jupyterlab/
            dockerfile: ./jupyterlab/Dockerfile.root
            tag_suffix: jlab:betif-alma9-cpu-with-root
            has_build_args: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          outputs: type=registry,push=true
          tags: ghcr.io/${{ env.repo_owner }}/${{ matrix.tag_suffix }}-${{ env.RELEASE_VERSION }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          build-args: ${{ matrix.has_build_arg && format('NOTEBOOK_VERSION={0}', env.RELEASE_VERSION) || '' }}
